version: "3.4"
volumes:
  data:
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: tiw2
    volumes:
      - ./data:/home/data
