version: "3.4"
services:
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: interop
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
