version: "3.4"
volumes:
  data:
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: tiw2
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
