version: "3.4"
volumes:
  data:
services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: chinook
    volumes:
      - ./postgres-data:/var/lib/postgresql
